In [302]:
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader
import numpy as np


In [303]:
dataset=pd.read_csv('EncodedFinalDataset.csv')

In [304]:
dataset.head(3)

Price  Bedrooms  Bathrooms  Land_Area    Year  Status_For Rent  \
0     70000.0       1.0        2.0      148.0  2025.0              1.0   
1    100000.0       3.0        2.0      148.0  2025.0              1.0   
2  31000000.0       5.0        3.0      350.0  2025.0              0.0   

   Status_For Sale  Furnished_No  Furnished_Yes  Address_Addis Ketema  ...  \
0              0.0           0.0            1.0                   0.0  ...   
1              0.0           0.0            1.0                   0.0  ...   
2              1.0           1.0            0.0                   0.0  ...   

   Address_Bole  Address_Gullele  Address_Kirkos  Address_Kolfe Keranio  \
0           0.0              0.0             0.0                    0.0   
1           0.0              0.0             0.0                    0.0   
2           0.0              0.0             0.0                    0.0   

   Address_Lemi Kura  Address_Lideta  Address_Nifas Silk-Lafto  Address_Yeka  \
0                0.0             0.0                       0.0           1.0   
1                1.0             0.0                       0.0           0.0   
2                1.0             0.0                       0.0           0.0   

   Property_Type_Apartment  Property_Type_Villa  
0                      1.0                  0.0  
1                      1.0                  0.0  
2                      0.0                  1.0  

[3 rows x 22 columns]

In [305]:
dataset.shape

(7659, 22)

In [306]:
# X=dataset[1:]
# Y=dataset[0]


In [307]:
# X[:5,:],Y[:5,:]

In [308]:
dataset=torch.tensor(dataset.values,dtype=torch.float32)
dataset.type

<function Tensor.type>

In [309]:
X=dataset[:,1:]
Y=dataset[:,0]
Y=Y.view(-1,1)


In [310]:
X[:3,:]

tensor([[1.0000e+00, 2.0000e+00, 1.4800e+02, 2.0250e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         1.0000e+00, 1.0000e+00, 0.0000e+00],
        [3.0000e+00, 2.0000e+00, 1.4800e+02, 2.0250e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 1.0000e+00, 0.0000e+00],
        [5.0000e+00, 3.0000e+00, 3.5000e+02, 2.0250e+03, 0.0000e+00, 1.0000e+00,
         1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 1.0000e+00]])

In [311]:
X.shape,Y.shape

(torch.Size([7659, 21]), torch.Size([7659, 1]))

In [312]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

(torch.Size([6127, 21]),
 torch.Size([1532, 21]),
 torch.Size([6127, 1]),
 torch.Size([1532, 1]))

In [313]:
mean=X_train.mean(dim=0)
torch.save(mean,"mean.pt")
std=X_train.std(dim=0)
torch.save(std,"std.pt")



In [314]:
X_train=(X_train-mean)/std
X_test=(X_test-mean)/std


In [315]:
Y_mean = Y_train.mean()
Y_std = Y_train.std()
Y_train = (Y_train - Y_mean) / Y_std
Y_test= (Y_test - Y_mean) / Y_std  

In [316]:
mean,std

(tensor([3.0664e+00, 2.5577e+00, 1.9923e+02, 2.0248e+03, 4.4900e-01, 5.5100e-01,
         5.3844e-01, 4.6156e-01, 1.0935e-02, 7.5078e-03, 2.3992e-02, 5.5574e-01,
         2.7746e-03, 6.9692e-02, 1.2241e-02, 6.0715e-02, 1.7627e-02, 4.9127e-02,
         1.8965e-01, 8.6062e-01, 1.3938e-01]),
 tensor([2.0620e+00, 1.5786e+00, 2.6714e+02, 4.2303e-01, 4.9743e-01, 4.9743e-01,
         4.9856e-01, 4.9856e-01, 1.0401e-01, 8.6328e-02, 1.5304e-01, 4.9692e-01,
         5.2606e-02, 2.5465e-01, 1.0997e-01, 2.3883e-01, 1.3160e-01, 2.1615e-01,
         3.9206e-01, 3.4637e-01, 3.4637e-01]))

In [317]:
X_train.mean(dim=0),X_train.std(dim=0)


(tensor([ 2.9885e-08,  3.1753e-08, -2.4904e-09,  1.2215e-04, -1.9612e-08,
          1.9612e-08, -1.5565e-08,  3.9535e-08, -2.9885e-08, -1.5487e-08,
         -1.4787e-08, -9.3391e-10, -6.3039e-09, -2.4904e-08, -5.6034e-09,
          2.7395e-08,  1.8678e-08,  2.4904e-08,  5.0742e-08,  3.5488e-08,
         -1.4943e-08]),
 tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000]))

In [318]:
X_train.shape

torch.Size([6127, 21])

In [319]:
class RevoNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1=nn.Linear(21,256)
        self.fc2Seq=nn.Sequential(
            nn.Linear(256,128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128,64),
            nn.ReLU(),
            nn.Linear(64,32),
            nn.Dropout(0.2),
            nn.ReLU(),
            nn.Linear(32,16),
          
        )
        self.dropout=nn.Dropout(0.2)
        self.fc6=nn.Linear(16,1)

      
        
    def forward(self,x):
        x=self.fc1(x)
        x=self.fc2Seq(x)
        x=self.dropout(x)
        x=self.fc6(x)
       
        return x


In [320]:
model=RevoNeuralNetwork()


In [321]:
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)
lossfun = nn.L1Loss()


In [ ]:
train_dataset = TensorDataset(X_train, Y_train)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
import matplotlib.pyplot as plt
trainLossavg = []
testLoss = []
trainMAEavg = []
testMAE = []

for epoch in range(200):
    batchLoss = []
    batchMAE = []
    total_samples = 0  

    model.train()
    for X_batch, Y_batch in train_loader:
        numofsample = X_batch.shape[0]  
        y_pred = model(X_batch)
        loss = lossfun(y_pred, Y_batch)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        batch_mae = torch.mean(torch.abs(y_pred - Y_batch)).item()
        batchLoss.append(loss.item() * numofsample)  
        batchMAE.append(batch_mae * numofsample)
        total_samples += numofsample

    epoch_loss_avg = sum(batchLoss) / total_samples
    epoch_mae_avg = sum(batchMAE) / total_samples
    trainLossavg.append(epoch_loss_avg)
    trainMAEavg.append(epoch_mae_avg)
    
    model.eval()
    with torch.no_grad():
        y_pred_test = model(X_test)
        test_loss = lossfun(y_pred_test, Y_test)
        test_mae = torch.mean(torch.abs(y_pred_test - Y_test)).item()
        testLoss.append(test_loss.item())
        testMAE.append(test_mae)
    
    if epoch % 10 == 0:
        print(f'Epoch {epoch}:')
        print(f'Train Loss: {epoch_loss_avg:.4f}, Train MAE: {epoch_mae_avg:.4f}')
        print(f'Test Loss: {test_loss.item():.4f}, Test MAE: {test_mae:.4f}')

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(trainLossavg, label='Train Loss')
plt.plot(testLoss, label='Test Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Training and Testing Loss')

plt.subplot(1, 2, 2)
plt.plot(trainMAEavg, label='Train MAE')
plt.plot(testMAE, label='Test MAE')
plt.xlabel('Epoch')
plt.ylabel('MAE')
plt.legend()
plt.title('Training and Testing MAE')
plt.tight_layout()
plt.show()

print("\nFinal Results:")
print(f"Final Train Loss: {trainLossavg[-1]:.4f}")
print(f"Final Test Loss: {testLoss[-1]:.4f}")
print(f"Final Train MAE: {trainMAEavg[-1]:.4f}")
print(f"Final Test MAE: {testMAE[-1]:.4f}")

Epoch 0:
Train Loss: 0.1556, Train MAE: 0.1556
Test Loss: 0.0903, Test MAE: 0.0903
Epoch 10:
Train Loss: 0.1092, Train MAE: 0.1092
Test Loss: 0.0684, Test MAE: 0.0684
Epoch 20:
Train Loss: 0.1031, Train MAE: 0.1031
Test Loss: 0.0663, Test MAE: 0.0663
Epoch 30:
Train Loss: 0.1008, Train MAE: 0.1008
Test Loss: 0.0601, Test MAE: 0.0601
Epoch 40:
Train Loss: 0.0993, Train MAE: 0.0993
Test Loss: 0.0637, Test MAE: 0.0637
Epoch 50:
Train Loss: 0.0979, Train MAE: 0.0979
Test Loss: 0.0634, Test MAE: 0.0634


In [ ]:
X_test.shape

torch.Size([1532, 21])

In [ ]:
raw_input = [3.0, 2.0, 140.0, 2025.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

input_tensor = torch.tensor(raw_input, dtype=torch.float32).unsqueeze(0)  # Shape: (1, 22)



input_tensor_scaled = (input_tensor - mean) / std

model.eval() 
with torch.no_grad():
    y_pred = model(input_tensor_scaled)
    y_pred_raw = (y_pred.item() * Y_std) + Y_mean
    print(f'Prediction: {y_pred_raw}')  # Use .item() if single value

Prediction: 12992548.0
